export const GET_STUDENTS = 'GET_STUDENTS';
export const STUDENT_ERROR = 'STUDENT_ERROR';
export const ADD_STUDENT = 'ADD_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const FILTER_STUDENTS = 'FILTER_STUDENTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const ADD_STUDENT_FAIL = 'ADD_STUDENT_FAIL';
export const CLEAR_STUDENTS = 'CLEAR_STUDENTS';
export const GET_STUDENT = 'GET_STUDENT';
export const UPDATE_OWN_SELECTIONS = 'UPDATE_OWN_SELECTIONS';
export const UPDATE_CURRENT_CHOICES = 'UPDATE_CURRENT_CHOICES';
export const SUBMIT_SELECTIONS = 'SUBMIT_SELECTIONS';

export const CHECK_STUDENT = 'CHECK_STUDENT';
export const SET_CHECKED_STUDENT = 'SET_CHECKED_STUDENT';
export const UNCHECK_STUDENT = 'UNCHECK_STUDENT';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const DELETE_USER = 'DELETE_USER';

export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export const GET_CAMPAIGNS = 'GET_CAMPAIGNS';
export const CAMPAIGN_ERROR = 'CAMPAIGN_ERROR';
export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN';
export const SET_ACADEMIC_YEAR = 'SET_ACADEMIC_YEAR';
export const CLEAR_ACADEMIC_YEAR = 'CLEAR_ACADEMIC_YEAR';
export const SET_CURRENT_CAMPAIGN = 'SET_CURRENT_CAMPAIGN';
export const CLEAR_CURRENT_CAMPAIGN = 'CLEAR_CURRENT_CAMPAIGN';
export const GET_CURRENT_CAMPAIGN = 'GET_CURRENT_CAMPAIGN';


export const UPDATE_SELECTIONS = 'UPDATE_SELECTIONS';

