export const ADD_STUDENT = 'ADD_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const FILTER_STUDENTS = 'FILTER_STUDENTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const ADD_STUDENT_FAIL = 'ADD_STUDENT_FAIL';
export const CLEAR_STUDENTS = 'CLEAR_STUDENTS';



export const CHECK_STUDENT = 'CHECK_STUDENT';
export const UNCHECK_STUDENT = 'UNCHECK_STUDENT';


export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';


export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
